planning:
  epsilon: 100
  verbose: false
  verbose_collisions: false
  shortcut_path: false
  interpolate_path: false
  use_bfs_heuristic: true
  group_name: left_arm
  planning_joints:
    l_shoulder_pan_joint
    l_shoulder_lift_joint
    l_upper_arm_roll_joint
    l_elbow_flex_joint
    l_forearm_roll_joint
    l_wrist_flex_joint
    l_wrist_roll_joint
  discretization: 360 360 360 360 360 360 360

debug:
  print_out_path: false
  logging:
    expands: info
    expands2: debug
    ik: debug
    robot_model: debug
    collisions: debug
    solution: debug

visualizations:
  heuristic: false
  goal: true
  expanded_states: true
  trajectory: false
  collision_model_trajectory: false
  trajectory_throttle: 1

#  occupancy_grid:
#    origin_x: -0.75
#    origin_y: -1.25
#    origin_z: -0.05
#    size_x: 2.0
#    size_y: 2.0
#    size_z: 2.0

