planner:
  epsilon: 100
  verbose: false
  use_dijkstra_heuristic: true
  use_research_heuristic: false
  use_uniform_obstacle_cost: false
  use_multiresolution_motion_primitives: true
  obstacle_distance_cost_far: 2
  obstacle_distance_cost_mid: 7
  obstacle_distance_cost_near: 12
  research:
    solve_with_ik_threshold: 0.06
    sum_heuristics: false
    short_distance_mprims_threshold: 0.2
  
robot:
  arm_name: left_arm
  num_joints: 7
  
debug:
  print_out_path: false

visualizations:
  heuristic: true
  goal: true
  expanded_states: false
  trajectory: false
  collision_model_trajectory: false
  trajectory_throttle: 3

collision_space:
  group_name: left_arm
  reference_frame: base_footprint
  resolution: 0.01
  collision_map_topic: collision_map_occ

  occupancy_grid:
    origin_x: -0.60
    origin_y: -0.50
    origin_z: -0.05
    size_x: 1.7
    size_y: 1.9
    size_z: 2.0

planning_joints:
  l_shoulder_pan_joint
  l_shoulder_lift_joint
  l_upper_arm_roll_joint
  l_elbow_flex_joint
  l_forearm_roll_joint
  l_wrist_flex_joint
  l_wrist_roll_joint

reference_frame: base_footprint
fk_service_name: pr2_left_arm_kinematics/get_fk
ik_service_name: pr2_left_arm_kinematics/get_ik

