collision_groups:

  - name: right_arm
    planning_joints:
      r_shoulder_pan_joint
      r_shoulder_lift_joint
      r_upper_arm_roll_joint
      r_elbow_flex_joint
      r_forearm_roll_joint
      r_wrist_flex_joint
      r_wrist_roll_joint
    redundancy:
      name: r_upper_arm_roll_joint
    root_name: base_footprint
    tip_name: r_wrist_roll_link
    collision_links:
    - name: shoulder
      root: r_shoulder_pan_link
      spheres: sh0
    - name: upper_arm
      root: r_upper_arm_roll_link
      spheres: ua0 ua1 ua2 ua3
    - name: forearm
      root: r_forearm_roll_link
      spheres: fa0 fa1 fa2 fa3 fa4 fa5 fa6
    - name: gripper
      root: r_wrist_roll_link
      spheres: gr0 gr1 gr2
    - name: left_finger
      root: r_gripper_l_finger_link
      spheres: lf0 lf1
    - name: right_finger
      root: r_gripper_r_finger_link
      spheres: rf0 rf1
    - name: right_finger_tip
      root: r_gripper_r_finger_tip_link
      spheres: rft0 rft1
    - name: left_finger_tip
      root: r_gripper_l_finger_tip_link
      spheres: lft0 lft1


sh0: {x: 0.09, y: 0.0, z: 0.00, radius: 0.18, priority: 5}

ua0: {x: 0.18, y: 0.0, z: -0.015, radius: 0.11, priority: 4}
ua1: {x: 0.26, y: 0.00, z: -0.035, radius: 0.08, priority: 4}
ua2: {x: 0.3275, y: 0.00, z: -0.035, radius: 0.08, priority: 4}
ua3: {x: 0.40, y: 0.0, z: -0.0, radius: 0.105, priority: 2}

fa0: {x: 0.13, y: 0.0, z: 0.005, radius: 0.075, priority: 2}
fa1: {x: 0.20, y: 0.025, z: -0.01, radius: 0.055, priority: 3}
fa2: {x: 0.20, y: -0.025, z: -0.01, radius: 0.055, priority: 3}
fa3: {x: 0.265, y: 0.0275, z: -0.015, radius: 0.05, priority: 3}
fa4: {x: 0.265, y: -0.0275, z: -0.015, radius: 0.05, priority: 3}
fa5: {x: 0.32, y: 0.0225, z: -0.005, radius: 0.05, priority: 3}
fa6: {x: 0.32, y: -0.0225, z: -0.005, radius: 0.05, priority: 3}

#fa0: {x: 0.12, y: 0.0, z: 0.01, radius: 0.07, priority: 2}
#fa1: {x: 0.19, y: 0.0, z: -0.01, radius: 0.06, priority: 3}
#fa2: {x: 0.25, y: 0.0, z: -0.01, radius: 0.06, priority: 3}
#fa3: {x: 0.32, y: 0.0, z: -0.01, radius: 0.06, priority: 3}
#fa4: {x: 0.34, y: 0.04, z: 0.01, radius: 0.03, priority: 3}
#fa5: {x: 0.34, y: -0.04, z: 0.01, radius: 0.03, priority: 3}

gr0: {x: 0.0725, y: -0.0175, z: 0.00, radius: 0.04, priority: 2}
gr1: {x: 0.0725, y: 0.0175, z: 0.00, radius: 0.04, priority: 2}
gr2: {x: 0.0925, y: 0.0, z: 0.00, radius: 0.04, priority: 2}

lf0: {x: 0.03, y: 0.025, z: 0.00, radius: 0.04, priority: 1}
lf1: {x: 0.08, y: 0.0175, z: 0.00, radius: 0.035, priority: 1}

rf0: {x: 0.03, y: -0.025, z: 0.00, radius: 0.04, priority: 1}
rf1: {x: 0.08, y: -0.0175, z: 0.00, radius: 0.035, priority: 1}

rft0: {x: 0.015, y: 0.005, z: 0.00, radius: 0.03, priority: 1}
rft1: {x: 0.035, y: 0.005, z: 0.00, radius: 0.02, priority: 1}

lft0: {x: 0.015, y: -0.005, z: 0.00, radius: 0.03, priority: 1}
lft1: {x: 0.035, y: -0.005, z: 0.00, radius: 0.02, priority: 1}

